[package]
name = "tree-sitter-PARSER_NAME"
description = "PARSER_NAME grammar for the tree-sitter parsing library"
version = "0.0.1"
keywords = ["incremental", "parsing", "PARSER_NAME"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-PARSER_NAME"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~RUST_BINDING_VERSION"
# tree-sitter = "0.17"
# tree-sitter = "0.25.10"

[build-dependencies]
cc = "1.0"
